"""Removed TeamBySeason and PlayerBySeason relation

Revision ID: 789f8f6ebf32
Revises: 60e0e7a2ffa9
Create Date: 2025-04-29 17:05:13.169470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '789f8f6ebf32'
down_revision: Union[str, None] = '60e0e7a2ffa9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
