"""Removed TeamBySeason and PlayerBySeason relation

Revision ID: d6b1e36250c8
Revises: 789f8f6ebf32
Create Date: 2025-04-29 17:09:49.906148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6b1e36250c8'
down_revision: Union[str, None] = '789f8f6ebf32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_game_log', sa.Column('season_id', sa.Integer(), nullable=False))
    op.add_column('team_game_log', sa.Column('team_season_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'team_game_log', 'team_by_seasons', ['team_season_id'], ['id'])
    op.create_foreign_key(None, 'team_game_log', 'seasons', ['season_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'team_game_log', type_='foreignkey')
    op.drop_constraint(None, 'team_game_log', type_='foreignkey')
    op.drop_column('team_game_log', 'team_season_id')
    op.drop_column('team_game_log', 'season_id')
    # ### end Alembic commands ###
