"""Models revisions

Revision ID: e82e1b9e92d8
Revises: d6b1e36250c8
Create Date: 2025-05-01 10:40:47.966450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e82e1b9e92d8'
down_revision: Union[str, None] = 'd6b1e36250c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('games_away_team_id_fkey', 'games', type_='foreignkey')
    op.drop_constraint('games_home_team_id_fkey', 'games', type_='foreignkey')
    op.create_foreign_key(None, 'games', 'team_by_seasons', ['away_team_id'], ['id'])
    op.create_foreign_key(None, 'games', 'team_by_seasons', ['home_team_id'], ['id'])
    op.add_column('player_game_log', sa.Column('season_id', sa.Integer(), nullable=False))
    op.add_column('player_game_log', sa.Column('player_season_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'player_game_log', 'player_by_seasons', ['player_season_id'], ['id'])
    op.create_foreign_key(None, 'player_game_log', 'seasons', ['season_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'player_game_log', type_='foreignkey')
    op.drop_constraint(None, 'player_game_log', type_='foreignkey')
    op.drop_column('player_game_log', 'player_season_id')
    op.drop_column('player_game_log', 'season_id')
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.create_foreign_key('games_home_team_id_fkey', 'games', 'teams', ['home_team_id'], ['id'])
    op.create_foreign_key('games_away_team_id_fkey', 'games', 'teams', ['away_team_id'], ['id'])
    # ### end Alembic commands ###
